[package]
edition = "2018"
name = "syntax_base"
version = "0.1.0"
authors = ["Roman.Ivanov <Roman.Ivanov@jetbrains.com>"]

[dependencies]
rowan = "0.1.3"
text_unit = "0.1.5"
drop_bomb = "0.1.4"
smol_str = "0.1.8"
